name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: nu.nerd.itemlocker.ItemLocker
softdepend: []
depend: [WorldGuard]

permissions:
  itemlocker.console:
    description: Permission to use commands that require console access.
    default: op

  itemlocker.bypass:
    description: Permission to bypass ownership checks on frames and stands. They can be unlocked and locked to anyone.
    default: op

  itemlocker.user:
    description: Permission to use /ipersist, /ilock, /imodify, /iunlock and /iinfo.
    default: op

commands:
  itemlocker:
    description: Administrative command.
    permission: itemlocker.console
    usage: |
      §e/<command> help§f - Show usage help.
      §e/<command> reload§f - Reload the plugin configuration. 
  
  ibypass:
    description: Toggle bypassing ownership checks.
    permission: itemlocker.bypass
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Toggles bypass mode. In bypass mode, you can 
        execute commands on frames and stands even if you are
        neither owner nor a region member.

  ipersist:
    description: Toggle persistent commands.
    permission: itemlocker.user
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Keep executing the next frame/stand command until
        you run /ipersist again.

  ilock:
    description: Lock an item frame or armor stand.
    permission: itemlocker.user
    usage: |
      
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§er:<region>§f] [§e<access and rotate permissions>§f]
        - Lock the next frame or stand you place or right click,
          optionally specifying a WorldGuard region whose owners and
          members also have access. See §e/help imodify§f for an
          explanation of access and rotate permissions.
      §e/<command> <player> §f[§er:<region>§f] [§e<access and rotate permissions>§f] 
        - Staff variant: lock a frame or stand on behalf of the
          specified player and optional WorldGuard region with
          optional access/rotate permissions.

  imodify:
    description: Change the region and/or permission groups of an item frame or armor stand.
    permission: itemlocker.user
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§er:<region>§f] [(§e-§f|§e+§f|§e*§f)§eaccess§f] [(§e-§f|§e+§f|§e*§f)§erotate§f] 
        - Change the region and/or permission groups of a frame or
          stand. Use §e/<command> r:-§f to clear an existing region.
          Item frames record §eaccess§f and §erotate§f groups, whereas
          armor stands only record the former. The §eaccess§f group
          (which can be abbreviated as §ea§f) is the set of players that
          can put into and take from the frame/stand. The §erotate§f group
          (which can be abbreviated as §er§f), is the set of players that
          can rotate the frame. Each group can be one of three
          settings: nobody (§e-§f), members (§e+§f), or public (§e*§f).
          Example: §e/<command> r:my_region +a *r§f
          allows only the frame/stand owner and owners/members of
          WorldGuard region "my_region" to access items held by the
          frame or stand, but allows any player to rotate it. Note that
          access and rotate permissions can be set without changing
          the region, if desired.
        
  iunlock:
    description: Unlock an item frame or armor stand.
    permission: itemlocker.user
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Unlock the next frame/stand you right click on. You
        must be its owner or an owner/member of its region to unlock
        it.

  iinfo:
    description: Show the permissions of an item frame or armor stand.
    permission: itemlocker.user
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Show the permissions of the next item frame or
      armor stand you right click on.
    
  idefault:
    description: Set default permissions of item frames and stands when locked.
    permission: itemlocker.user
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§er:<region>§f] [(§e-§f|§e+§f|§e*§f)§eaccess§f] [(§e-§f|§e+§f|§e*§f)§erotate§f]
        - Set default permissions of item frames and stands when
          locked. These permissions are overridden by the permissions
          specified in an §e/ilock§f command. See §e/help imodify§f for details
          on the meaning of the arguments.
